///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace StudyRanorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the StudyRanorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    [RepositoryFolder("5ad22a55-74e6-4bad-aaf6-a920fcbc142f")]
    public partial class StudyRanorexRepository : RepoGenBaseFolder
    {
        static StudyRanorexRepository instance = new StudyRanorexRepository();
        StudyRanorexRepositoryFolders.AAAppFolder _aa;
        StudyRanorexRepositoryFolders.AADocumentsAppFolder _aadocuments;

        /// <summary>
        /// Gets the singleton class instance representing the StudyRanorexRepository element repository.
        /// </summary>
        [RepositoryFolder("5ad22a55-74e6-4bad-aaf6-a920fcbc142f")]
        public static StudyRanorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public StudyRanorexRepository() 
            : base("StudyRanorexRepository", "/", null, 0, false, "5ad22a55-74e6-4bad-aaf6-a920fcbc142f", ".\\RepositoryImages\\StudyRanorexRepository5ad22a55.rximgres")
        {
            _aa = new StudyRanorexRepositoryFolders.AAAppFolder(this);
            _aadocuments = new StudyRanorexRepositoryFolders.AADocumentsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5ad22a55-74e6-4bad-aaf6-a920fcbc142f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AA folder.
        /// </summary>
        [RepositoryFolder("70dbb9a2-f881-4f7b-a76f-62f9a618a5e1")]
        public virtual StudyRanorexRepositoryFolders.AAAppFolder AA
        {
            get { return _aa; }
        }

        /// <summary>
        /// The AADocuments folder.
        /// </summary>
        [RepositoryFolder("e4fd77af-c112-40a5-bd98-0e7a684d0f50")]
        public virtual StudyRanorexRepositoryFolders.AADocumentsAppFolder AADocuments
        {
            get { return _aadocuments; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    public partial class StudyRanorexRepositoryFolders
    {
        /// <summary>
        /// The AAAppFolder folder.
        /// </summary>
        [RepositoryFolder("70dbb9a2-f881-4f7b-a76f-62f9a618a5e1")]
        public partial class AAAppFolder : RepoGenBaseFolder
        {
            StudyRanorexRepositoryFolders.HomePageFolder _homepage;
            StudyRanorexRepositoryFolders.WrongCredsPageFolder _wrongcredspage;
            StudyRanorexRepositoryFolders.SearchResultsFolder _searchresults;
            StudyRanorexRepositoryFolders.MainMenuFolder _mainmenu;

            /// <summary>
            /// Creates a new AA  folder.
            /// </summary>
            public AAAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AA", "/dom[@domain='www.aa.com']", parentFolder, 30000, null, true, "70dbb9a2-f881-4f7b-a76f-62f9a618a5e1", "")
            {
                _homepage = new StudyRanorexRepositoryFolders.HomePageFolder(this);
                _wrongcredspage = new StudyRanorexRepositoryFolders.WrongCredsPageFolder(this);
                _searchresults = new StudyRanorexRepositoryFolders.SearchResultsFolder(this);
                _mainmenu = new StudyRanorexRepositoryFolders.MainMenuFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("70dbb9a2-f881-4f7b-a76f-62f9a618a5e1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("70dbb9a2-f881-4f7b-a76f-62f9a618a5e1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HomePage folder.
            /// </summary>
            [RepositoryFolder("4febf9ac-860d-4e4e-a9b3-82284527af20")]
            public virtual StudyRanorexRepositoryFolders.HomePageFolder HomePage
            {
                get { return _homepage; }
            }

            /// <summary>
            /// The WrongCredsPage folder.
            /// </summary>
            [RepositoryFolder("d21b4a32-4a9b-4e9f-bc86-9d923ff6bb8d")]
            public virtual StudyRanorexRepositoryFolders.WrongCredsPageFolder WrongCredsPage
            {
                get { return _wrongcredspage; }
            }

            /// <summary>
            /// The SearchResults folder.
            /// </summary>
            [RepositoryFolder("58fade16-1285-40fd-9e29-8f40d7b925ef")]
            public virtual StudyRanorexRepositoryFolders.SearchResultsFolder SearchResults
            {
                get { return _searchresults; }
            }

            /// <summary>
            /// The MainMenu folder.
            /// </summary>
            [RepositoryFolder("920cae0e-3202-41fd-9c4d-6194bd0ebd7f")]
            public virtual StudyRanorexRepositoryFolders.MainMenuFolder MainMenu
            {
                get { return _mainmenu; }
            }
        }

        /// <summary>
        /// The HomePageFolder folder.
        /// </summary>
        [RepositoryFolder("4febf9ac-860d-4e4e-a9b3-82284527af20")]
        public partial class HomePageFolder : RepoGenBaseFolder
        {
            StudyRanorexRepositoryFolders.LoginPanelFolder _loginpanel;
            StudyRanorexRepositoryFolders.ReservationFolder _reservation;

            /// <summary>
            /// Creates a new HomePage  folder.
            /// </summary>
            public HomePageFolder(RepoGenBaseFolder parentFolder) :
                    base("HomePage", "body/section/div", parentFolder, 30000, null, false, "4febf9ac-860d-4e4e-a9b3-82284527af20", "")
            {
                _loginpanel = new StudyRanorexRepositoryFolders.LoginPanelFolder(this);
                _reservation = new StudyRanorexRepositoryFolders.ReservationFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4febf9ac-860d-4e4e-a9b3-82284527af20")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4febf9ac-860d-4e4e-a9b3-82284527af20")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LoginPanel folder.
            /// </summary>
            [RepositoryFolder("3124d6c8-f2c9-4006-ab81-2614cfd7ae2d")]
            public virtual StudyRanorexRepositoryFolders.LoginPanelFolder LoginPanel
            {
                get { return _loginpanel; }
            }

            /// <summary>
            /// The Reservation folder.
            /// </summary>
            [RepositoryFolder("5697e974-9a15-4f45-b25c-25e57f8e4f64")]
            public virtual StudyRanorexRepositoryFolders.ReservationFolder Reservation
            {
                get { return _reservation; }
            }
        }

        /// <summary>
        /// The LoginPanelFolder folder.
        /// </summary>
        [RepositoryFolder("3124d6c8-f2c9-4006-ab81-2614cfd7ae2d")]
        public partial class LoginPanelFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fldusernameInfo;
            RepoItemInfo _fldlastnameInfo;
            RepoItemInfo _fldpwdInfo;
            RepoItemInfo _btnloginInfo;

            /// <summary>
            /// Creates a new LoginPanel  folder.
            /// </summary>
            public LoginPanelFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginPanel", "div/div/div/div/div[@class='row']/div/article/form", parentFolder, 30000, null, false, "3124d6c8-f2c9-4006-ab81-2614cfd7ae2d", "")
            {
                _fldusernameInfo = new RepoItemInfo(this, "fldUserName", "label[@innertext~'AAdvantage']/input", 30000, null, "6d848daa-ce5e-4e2d-83f7-69474e00890c");
                _fldlastnameInfo = new RepoItemInfo(this, "fldLastName", "label[@innertext~'Last\\ name']/input", 30000, null, "9819f9e0-8b5d-4f5f-853c-56f9a1c57f9a");
                _fldpwdInfo = new RepoItemInfo(this, "fldPwd", "label[@innertext~'Password']/input", 30000, null, "25672d12-1e67-4898-b907-d49639a2643f");
                _btnloginInfo = new RepoItemInfo(this, "btnLogIn", "div/div/input[@name='_button_go']", 30000, null, "87c967d4-79df-4020-98f7-5e521880af31");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3124d6c8-f2c9-4006-ab81-2614cfd7ae2d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3124d6c8-f2c9-4006-ab81-2614cfd7ae2d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The fldUserName item.
            /// </summary>
            [RepositoryItem("6d848daa-ce5e-4e2d-83f7-69474e00890c")]
            public virtual Ranorex.InputTag fldUserName
            {
                get
                {
                    return _fldusernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldUserName item info.
            /// </summary>
            [RepositoryItemInfo("6d848daa-ce5e-4e2d-83f7-69474e00890c")]
            public virtual RepoItemInfo fldUserNameInfo
            {
                get
                {
                    return _fldusernameInfo;
                }
            }

            /// <summary>
            /// The fldLastName item.
            /// </summary>
            [RepositoryItem("9819f9e0-8b5d-4f5f-853c-56f9a1c57f9a")]
            public virtual Ranorex.InputTag fldLastName
            {
                get
                {
                    return _fldlastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldLastName item info.
            /// </summary>
            [RepositoryItemInfo("9819f9e0-8b5d-4f5f-853c-56f9a1c57f9a")]
            public virtual RepoItemInfo fldLastNameInfo
            {
                get
                {
                    return _fldlastnameInfo;
                }
            }

            /// <summary>
            /// The fldPwd item.
            /// </summary>
            [RepositoryItem("25672d12-1e67-4898-b907-d49639a2643f")]
            public virtual Ranorex.InputTag fldPwd
            {
                get
                {
                    return _fldpwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldPwd item info.
            /// </summary>
            [RepositoryItemInfo("25672d12-1e67-4898-b907-d49639a2643f")]
            public virtual RepoItemInfo fldPwdInfo
            {
                get
                {
                    return _fldpwdInfo;
                }
            }

            /// <summary>
            /// The btnLogIn item.
            /// </summary>
            [RepositoryItem("87c967d4-79df-4020-98f7-5e521880af31")]
            public virtual Ranorex.InputTag btnLogIn
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The btnLogIn item info.
            /// </summary>
            [RepositoryItemInfo("87c967d4-79df-4020-98f7-5e521880af31")]
            public virtual RepoItemInfo btnLogInInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }
        }

        /// <summary>
        /// The ReservationFolder folder.
        /// </summary>
        [RepositoryFolder("5697e974-9a15-4f45-b25c-25e57f8e4f64")]
        public partial class ReservationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fldfromInfo;
            RepoItemInfo _fldtoInfo;
            RepoItemInfo _flddepartInfo;
            RepoItemInfo _fldreturnInfo;
            RepoItemInfo _bntsearchInfo;

            /// <summary>
            /// Creates a new Reservation  folder.
            /// </summary>
            public ReservationFolder(RepoGenBaseFolder parentFolder) :
                    base("Reservation", "div/div/div/div/div/div/div[#'booking-module-tabs']/div/form[#'reservationFlightSearchForm']", parentFolder, 30000, null, false, "5697e974-9a15-4f45-b25c-25e57f8e4f64", "")
            {
                _fldfromInfo = new RepoItemInfo(this, "fldFrom", "div/div/div/label[@innertext~'From']/input", 30000, null, "8162f011-c780-4a5a-b018-7d382f3582d9");
                _fldtoInfo = new RepoItemInfo(this, "fldTo", "div/div/div/label[@innertext~'To']/input", 30000, null, "02dfd410-2b2a-4b30-b58a-0d20395a860c");
                _flddepartInfo = new RepoItemInfo(this, "fldDepart", "div/div/div/label[@innertext~'Depart']/input", 30000, null, "bfe1d4ee-fb01-48c2-880b-6b234a1952c5");
                _fldreturnInfo = new RepoItemInfo(this, "fldReturn", "div/div/div/label[@innertext~'Return']/input", 30000, null, "b1b677af-bdb4-4c48-896c-2e5da3128005");
                _bntsearchInfo = new RepoItemInfo(this, "bntSearch", "div/div/div/input[@value='Search']", 30000, null, "f20360d0-5fd1-4e85-93ac-e550b2f237d3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5697e974-9a15-4f45-b25c-25e57f8e4f64")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5697e974-9a15-4f45-b25c-25e57f8e4f64")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The fldFrom item.
            /// </summary>
            [RepositoryItem("8162f011-c780-4a5a-b018-7d382f3582d9")]
            public virtual Ranorex.InputTag fldFrom
            {
                get
                {
                    return _fldfromInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldFrom item info.
            /// </summary>
            [RepositoryItemInfo("8162f011-c780-4a5a-b018-7d382f3582d9")]
            public virtual RepoItemInfo fldFromInfo
            {
                get
                {
                    return _fldfromInfo;
                }
            }

            /// <summary>
            /// The fldTo item.
            /// </summary>
            [RepositoryItem("02dfd410-2b2a-4b30-b58a-0d20395a860c")]
            public virtual Ranorex.InputTag fldTo
            {
                get
                {
                    return _fldtoInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldTo item info.
            /// </summary>
            [RepositoryItemInfo("02dfd410-2b2a-4b30-b58a-0d20395a860c")]
            public virtual RepoItemInfo fldToInfo
            {
                get
                {
                    return _fldtoInfo;
                }
            }

            /// <summary>
            /// The fldDepart item.
            /// </summary>
            [RepositoryItem("bfe1d4ee-fb01-48c2-880b-6b234a1952c5")]
            public virtual Ranorex.InputTag fldDepart
            {
                get
                {
                    return _flddepartInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldDepart item info.
            /// </summary>
            [RepositoryItemInfo("bfe1d4ee-fb01-48c2-880b-6b234a1952c5")]
            public virtual RepoItemInfo fldDepartInfo
            {
                get
                {
                    return _flddepartInfo;
                }
            }

            /// <summary>
            /// The fldReturn item.
            /// </summary>
            [RepositoryItem("b1b677af-bdb4-4c48-896c-2e5da3128005")]
            public virtual Ranorex.InputTag fldReturn
            {
                get
                {
                    return _fldreturnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The fldReturn item info.
            /// </summary>
            [RepositoryItemInfo("b1b677af-bdb4-4c48-896c-2e5da3128005")]
            public virtual RepoItemInfo fldReturnInfo
            {
                get
                {
                    return _fldreturnInfo;
                }
            }

            /// <summary>
            /// The bntSearch item.
            /// </summary>
            [RepositoryItem("f20360d0-5fd1-4e85-93ac-e550b2f237d3")]
            public virtual Ranorex.InputTag bntSearch
            {
                get
                {
                    return _bntsearchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The bntSearch item info.
            /// </summary>
            [RepositoryItemInfo("f20360d0-5fd1-4e85-93ac-e550b2f237d3")]
            public virtual RepoItemInfo bntSearchInfo
            {
                get
                {
                    return _bntsearchInfo;
                }
            }
        }

        /// <summary>
        /// The WrongCredsPageFolder folder.
        /// </summary>
        [RepositoryFolder("d21b4a32-4a9b-4e9f-bc86-9d923ff6bb8d")]
        public partial class WrongCredsPageFolder : RepoGenBaseFolder
        {
            StudyRanorexRepositoryFolders.PopupFolder _popup;
            StudyRanorexRepositoryFolders.MainPageFolder _mainpage;

            /// <summary>
            /// Creates a new WrongCredsPage  folder.
            /// </summary>
            public WrongCredsPageFolder(RepoGenBaseFolder parentFolder) :
                    base("WrongCredsPage", "body", parentFolder, 30000, null, false, "d21b4a32-4a9b-4e9f-bc86-9d923ff6bb8d", "")
            {
                _popup = new StudyRanorexRepositoryFolders.PopupFolder(this);
                _mainpage = new StudyRanorexRepositoryFolders.MainPageFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d21b4a32-4a9b-4e9f-bc86-9d923ff6bb8d")]
            public virtual Ranorex.BodyTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d21b4a32-4a9b-4e9f-bc86-9d923ff6bb8d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Popup folder.
            /// </summary>
            [RepositoryFolder("b46993ad-c934-4149-8cf6-150ac9cfb3ca")]
            public virtual StudyRanorexRepositoryFolders.PopupFolder Popup
            {
                get { return _popup; }
            }

            /// <summary>
            /// The MainPage folder.
            /// </summary>
            [RepositoryFolder("df1911a2-cc50-4bef-9f75-c2b02278099d")]
            public virtual StudyRanorexRepositoryFolders.MainPageFolder MainPage
            {
                get { return _mainpage; }
            }
        }

        /// <summary>
        /// The PopupFolder folder.
        /// </summary>
        [RepositoryFolder("b46993ad-c934-4149-8cf6-150ac9cfb3ca")]
        public partial class PopupFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtcantloginInfo;
            RepoItemInfo _btnclosepopupInfo;

            /// <summary>
            /// Creates a new Popup  folder.
            /// </summary>
            public PopupFolder(RepoGenBaseFolder parentFolder) :
                    base("Popup", "div", parentFolder, 30000, null, false, "b46993ad-c934-4149-8cf6-150ac9cfb3ca", "")
            {
                _txtcantloginInfo = new RepoItemInfo(this, "txtCantLogin", "div[@id='loginMainErrorMsgDialog']/div/p[@innertext~'couldn''t\\ log' and @innertext~'account']", 30000, null, "6e3206ca-1d46-4d61-91cf-ba63b0026456");
                _btnclosepopupInfo = new RepoItemInfo(this, "btnClosePopup", "div/div/button[#'loginMainErrorMsgDialogButton0']/span", 30000, null, "ad61ebc8-f2b0-4793-bb1c-64347906e709");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b46993ad-c934-4149-8cf6-150ac9cfb3ca")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b46993ad-c934-4149-8cf6-150ac9cfb3ca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The txtCantLogin item.
            /// </summary>
            [RepositoryItem("6e3206ca-1d46-4d61-91cf-ba63b0026456")]
            public virtual Ranorex.PTag txtCantLogin
            {
                get
                {
                    return _txtcantloginInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The txtCantLogin item info.
            /// </summary>
            [RepositoryItemInfo("6e3206ca-1d46-4d61-91cf-ba63b0026456")]
            public virtual RepoItemInfo txtCantLoginInfo
            {
                get
                {
                    return _txtcantloginInfo;
                }
            }

            /// <summary>
            /// The btnClosePopup item.
            /// </summary>
            [RepositoryItem("ad61ebc8-f2b0-4793-bb1c-64347906e709")]
            public virtual Ranorex.SpanTag btnClosePopup
            {
                get
                {
                    return _btnclosepopupInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The btnClosePopup item info.
            /// </summary>
            [RepositoryItemInfo("ad61ebc8-f2b0-4793-bb1c-64347906e709")]
            public virtual RepoItemInfo btnClosePopupInfo
            {
                get
                {
                    return _btnclosepopupInfo;
                }
            }
        }

        /// <summary>
        /// The MainPageFolder folder.
        /// </summary>
        [RepositoryFolder("df1911a2-cc50-4bef-9f75-c2b02278099d")]
        public partial class MainPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lnkhomeInfo;

            /// <summary>
            /// Creates a new MainPage  folder.
            /// </summary>
            public MainPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MainPage", "header/div", parentFolder, 30000, null, false, "df1911a2-cc50-4bef-9f75-c2b02278099d", "")
            {
                _lnkhomeInfo = new RepoItemInfo(this, "lnkHome", "div[#'main-navigation']/a[@href='https://www.aa.com/homePage.do']/img", 30000, null, "07be59b2-ba39-4b1b-9ab4-3c937497ae5a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df1911a2-cc50-4bef-9f75-c2b02278099d")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df1911a2-cc50-4bef-9f75-c2b02278099d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lnkHome item.
            /// </summary>
            [RepositoryItem("07be59b2-ba39-4b1b-9ab4-3c937497ae5a")]
            public virtual Ranorex.ImgTag lnkHome
            {
                get
                {
                    return _lnkhomeInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The lnkHome item info.
            /// </summary>
            [RepositoryItemInfo("07be59b2-ba39-4b1b-9ab4-3c937497ae5a")]
            public virtual RepoItemInfo lnkHomeInfo
            {
                get
                {
                    return _lnkhomeInfo;
                }
            }
        }

        /// <summary>
        /// The SearchResultsFolder folder.
        /// </summary>
        [RepositoryFolder("58fade16-1285-40fd-9e29-8f40d7b925ef")]
        public partial class SearchResultsFolder : RepoGenBaseFolder
        {
            StudyRanorexRepositoryFolders.TabsFolder _tabs;
            RepoItemInfo _lnkrefundableInfo;
            RepoItemInfo _lnkbusinessInfo;
            RepoItemInfo _lnklowestfareInfo;

            /// <summary>
            /// Creates a new SearchResults  folder.
            /// </summary>
            public SearchResultsFolder(RepoGenBaseFolder parentFolder) :
                    base("SearchResults", "body/div", parentFolder, 30000, null, false, "58fade16-1285-40fd-9e29-8f40d7b925ef", "")
            {
                _tabs = new StudyRanorexRepositoryFolders.TabsFolder(this);
                _lnkrefundableInfo = new RepoItemInfo(this, "lnkRefundable", "div/div/div[#'matrix_date_search']/div/div/div/div/ul/li/a[@innertext~'Refundable']", 30000, null, "9d17e0f6-196b-46f9-aeef-8136c87063ff");
                _lnkbusinessInfo = new RepoItemInfo(this, "lnkBusiness", "div/div/div[#'matrix_date_search']/div/div/div/div/ul/li/a[@innertext~'Business']", 30000, null, "5c9dd4b0-ee9d-4a2f-88d5-851200ba028c");
                _lnklowestfareInfo = new RepoItemInfo(this, "lnkLowestFare", "div/div/div[#'matrix_date_search']/div/div/div/div/ul/li/a[@innertext~'Lowest\\ Fare']", 30000, null, "983b43b5-275c-4c8b-ba94-944da864f817");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("58fade16-1285-40fd-9e29-8f40d7b925ef")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("58fade16-1285-40fd-9e29-8f40d7b925ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lnkRefundable item.
            /// </summary>
            [RepositoryItem("9d17e0f6-196b-46f9-aeef-8136c87063ff")]
            public virtual Ranorex.ATag lnkRefundable
            {
                get
                {
                    return _lnkrefundableInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lnkRefundable item info.
            /// </summary>
            [RepositoryItemInfo("9d17e0f6-196b-46f9-aeef-8136c87063ff")]
            public virtual RepoItemInfo lnkRefundableInfo
            {
                get
                {
                    return _lnkrefundableInfo;
                }
            }

            /// <summary>
            /// The lnkBusiness item.
            /// </summary>
            [RepositoryItem("5c9dd4b0-ee9d-4a2f-88d5-851200ba028c")]
            public virtual Ranorex.ATag lnkBusiness
            {
                get
                {
                    return _lnkbusinessInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lnkBusiness item info.
            /// </summary>
            [RepositoryItemInfo("5c9dd4b0-ee9d-4a2f-88d5-851200ba028c")]
            public virtual RepoItemInfo lnkBusinessInfo
            {
                get
                {
                    return _lnkbusinessInfo;
                }
            }

            /// <summary>
            /// The lnkLowestFare item.
            /// </summary>
            [RepositoryItem("983b43b5-275c-4c8b-ba94-944da864f817")]
            public virtual Ranorex.ATag lnkLowestFare
            {
                get
                {
                    return _lnklowestfareInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The lnkLowestFare item info.
            /// </summary>
            [RepositoryItemInfo("983b43b5-275c-4c8b-ba94-944da864f817")]
            public virtual RepoItemInfo lnkLowestFareInfo
            {
                get
                {
                    return _lnklowestfareInfo;
                }
            }

            /// <summary>
            /// The tabs folder.
            /// </summary>
            [RepositoryFolder("92197d3a-fb26-42ad-baca-9f75b94fc456")]
            public virtual StudyRanorexRepositoryFolders.TabsFolder tabs
            {
                get { return _tabs; }
            }
        }

        /// <summary>
        /// The TabsFolder folder.
        /// </summary>
        [RepositoryFolder("92197d3a-fb26-42ad-baca-9f75b94fc456")]
        public partial class TabsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tabrefundableInfo;
            RepoItemInfo _tabbusinessInfo;
            RepoItemInfo _tablowestfareInfo;
            RepoItemInfo _slctsortInfo;

            /// <summary>
            /// Creates a new tabs  folder.
            /// </summary>
            public TabsFolder(RepoGenBaseFolder parentFolder) :
                    base("tabs", "div/div/div[#'matrix_date_search']/div/div/div/div[#'aa-matrix-departure-flights']", parentFolder, 30000, null, false, "92197d3a-fb26-42ad-baca-9f75b94fc456", "")
            {
                _tabrefundableInfo = new RepoItemInfo(this, "tabRefundable", "div/form[#'matrixRefundableFlightSearchDepartureForm']", 30000, null, "775ee7ba-882f-4dd6-87fb-52d01ffdaa71");
                _tabbusinessInfo = new RepoItemInfo(this, "tabBusiness", "div/form[#'matrixPremiumFlightSearchDepartureForm']", 30000, null, "f762e036-d744-4e57-962e-e91d20cbdbd7");
                _tablowestfareInfo = new RepoItemInfo(this, "tabLowestFare", "div/form[#'matrixLowestFlightSearchDepartureForm']", 30000, null, "3d832403-e55b-4e7b-aea0-a9e4f8cb9e7a");
                _slctsortInfo = new RepoItemInfo(this, "slctSort", "div/form/table/thead/tr/th/div/select[#'extsorterdeparturepremium']", 30000, null, "2ed41516-4194-4ae8-b94d-67ad44781b41");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("92197d3a-fb26-42ad-baca-9f75b94fc456")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("92197d3a-fb26-42ad-baca-9f75b94fc456")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The tabRefundable item.
            /// </summary>
            [RepositoryItem("775ee7ba-882f-4dd6-87fb-52d01ffdaa71")]
            public virtual Ranorex.Form tabRefundable
            {
                get
                {
                    return _tabrefundableInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The tabRefundable item info.
            /// </summary>
            [RepositoryItemInfo("775ee7ba-882f-4dd6-87fb-52d01ffdaa71")]
            public virtual RepoItemInfo tabRefundableInfo
            {
                get
                {
                    return _tabrefundableInfo;
                }
            }

            /// <summary>
            /// The tabBusiness item.
            /// </summary>
            [RepositoryItem("f762e036-d744-4e57-962e-e91d20cbdbd7")]
            public virtual Ranorex.Form tabBusiness
            {
                get
                {
                    return _tabbusinessInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The tabBusiness item info.
            /// </summary>
            [RepositoryItemInfo("f762e036-d744-4e57-962e-e91d20cbdbd7")]
            public virtual RepoItemInfo tabBusinessInfo
            {
                get
                {
                    return _tabbusinessInfo;
                }
            }

            /// <summary>
            /// The tabLowestFare item.
            /// </summary>
            [RepositoryItem("3d832403-e55b-4e7b-aea0-a9e4f8cb9e7a")]
            public virtual Ranorex.Form tabLowestFare
            {
                get
                {
                    return _tablowestfareInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The tabLowestFare item info.
            /// </summary>
            [RepositoryItemInfo("3d832403-e55b-4e7b-aea0-a9e4f8cb9e7a")]
            public virtual RepoItemInfo tabLowestFareInfo
            {
                get
                {
                    return _tablowestfareInfo;
                }
            }

            /// <summary>
            /// The slctSort item.
            /// </summary>
            [RepositoryItem("2ed41516-4194-4ae8-b94d-67ad44781b41")]
            public virtual Ranorex.SelectTag slctSort
            {
                get
                {
                    return _slctsortInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The slctSort item info.
            /// </summary>
            [RepositoryItemInfo("2ed41516-4194-4ae8-b94d-67ad44781b41")]
            public virtual RepoItemInfo slctSortInfo
            {
                get
                {
                    return _slctsortInfo;
                }
            }
        }

        /// <summary>
        /// The MainMenuFolder folder.
        /// </summary>
        [RepositoryFolder("920cae0e-3202-41fd-9c4d-6194bd0ebd7f")]
        public partial class MainMenuFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lnkhomeInfo;

            /// <summary>
            /// Creates a new MainMenu  folder.
            /// </summary>
            public MainMenuFolder(RepoGenBaseFolder parentFolder) :
                    base("MainMenu", "body/?/header/div", parentFolder, 30000, null, false, "920cae0e-3202-41fd-9c4d-6194bd0ebd7f", "")
            {
                _lnkhomeInfo = new RepoItemInfo(this, "lnkHome", "div[#'main-navigation']/a[@href='https://www.aa.com/homePage.do']/img", 30000, null, "d43189e2-16d0-4631-8f69-47b8a45d9f26");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("920cae0e-3202-41fd-9c4d-6194bd0ebd7f")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("920cae0e-3202-41fd-9c4d-6194bd0ebd7f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The lnkHome item.
            /// </summary>
            [RepositoryItem("d43189e2-16d0-4631-8f69-47b8a45d9f26")]
            public virtual Ranorex.ImgTag lnkHome
            {
                get
                {
                    return _lnkhomeInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The lnkHome item info.
            /// </summary>
            [RepositoryItemInfo("d43189e2-16d0-4631-8f69-47b8a45d9f26")]
            public virtual RepoItemInfo lnkHomeInfo
            {
                get
                {
                    return _lnkhomeInfo;
                }
            }
        }

        /// <summary>
        /// The AADocumentsAppFolder folder.
        /// </summary>
        [RepositoryFolder("e4fd77af-c112-40a5-bd98-0e7a684d0f50")]
        public partial class AADocumentsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _resultsInfo;

            /// <summary>
            /// Creates a new AADocuments  folder.
            /// </summary>
            public AADocumentsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AADocuments", "", parentFolder, 30000, null, true, "e4fd77af-c112-40a5-bd98-0e7a684d0f50", "")
            {
                _resultsInfo = new RepoItemInfo(this, "Results", "/dom[@domain='www.aa.com' and @caption~'Flight\\ results']", 30000, null, "cd1dea4b-c1f6-440c-9f87-71f47246a752");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e4fd77af-c112-40a5-bd98-0e7a684d0f50")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e4fd77af-c112-40a5-bd98-0e7a684d0f50")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Results item.
            /// </summary>
            [RepositoryItem("cd1dea4b-c1f6-440c-9f87-71f47246a752")]
            public virtual Ranorex.WebDocument Results
            {
                get
                {
                    return _resultsInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Results item info.
            /// </summary>
            [RepositoryItemInfo("cd1dea4b-c1f6-440c-9f87-71f47246a752")]
            public virtual RepoItemInfo ResultsInfo
            {
                get
                {
                    return _resultsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}